version: '3.8'
services:
  postgres:
    image: postgres:12
    restart: always
    container_name: discord-bot-database
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database: